title = "Home"
baseURL = "http://katherinechandler.io"
languageCode = "en-us"
theme = "ananke"
themesDir = "./themes"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Exploring the world, with data and otherwise"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/katherinechandler"
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-green"
  featured_image = "/images/new_default.jpg"
  recent_posts_number = 2
